# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/basys3.xdc

# Block Designs: bd/pps_generator/pps_generator.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pps_generator || ORIG_REF_NAME==pps_generator}]

# IP: bd/pps_generator/ip/pps_generator_pps_counter_100mhz_0_0/pps_generator_pps_counter_100mhz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pps_generator_pps_counter_100mhz_0_0 || ORIG_REF_NAME==pps_generator_pps_counter_100mhz_0_0}]

# IP: bd/pps_generator/ip/pps_generator_util_vector_logic_0_0/pps_generator_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pps_generator_util_vector_logic_0_0 || ORIG_REF_NAME==pps_generator_util_vector_logic_0_0}]

# IP: bd/pps_generator/ip/pps_generator_util_vector_logic_0_1/pps_generator_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pps_generator_util_vector_logic_0_1 || ORIG_REF_NAME==pps_generator_util_vector_logic_0_1}]

# IP: bd/pps_generator/ip/pps_generator_util_vector_logic_1_0/pps_generator_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pps_generator_util_vector_logic_1_0 || ORIG_REF_NAME==pps_generator_util_vector_logic_1_0}]

# IP: bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pps_generator_gen_event_trigger_0_0 || ORIG_REF_NAME==pps_generator_gen_event_trigger_0_0}]

# XDC: bd/pps_generator/pps_generator_ooc.xdc
