# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3.xdc

# Block Designs: bd/sync_counter_PPS/sync_counter_PPS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS || ORIG_REF_NAME==sync_counter_PPS}]

# IP: bd/sync_counter_PPS/ip/sync_counter_PPS_counter_pps_0_0/sync_counter_PPS_counter_pps_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS_counter_pps_0_0 || ORIG_REF_NAME==sync_counter_PPS_counter_pps_0_0}]

# IP: bd/sync_counter_PPS/ip/sync_counter_PPS_display_0_0/sync_counter_PPS_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS_display_0_0 || ORIG_REF_NAME==sync_counter_PPS_display_0_0}]

# IP: bd/sync_counter_PPS/ip/sync_counter_PPS_mem_counter_0_0/sync_counter_PPS_mem_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS_mem_counter_0_0 || ORIG_REF_NAME==sync_counter_PPS_mem_counter_0_0}]

# IP: bd/sync_counter_PPS/ip/sync_counter_PPS_UART_0_0/sync_counter_PPS_UART_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS_UART_0_0 || ORIG_REF_NAME==sync_counter_PPS_UART_0_0}]

# IP: bd/sync_counter_PPS/ip/sync_counter_PPS_fifo_generator_0_0_1/sync_counter_PPS_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS_fifo_generator_0_0 || ORIG_REF_NAME==sync_counter_PPS_fifo_generator_0_0}]

# IP: bd/sync_counter_PPS/ip/sync_counter_PPS_inputs_0_0/sync_counter_PPS_inputs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS_inputs_0_0 || ORIG_REF_NAME==sync_counter_PPS_inputs_0_0}]

# IP: bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/sync_counter_PPS_system_ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_counter_PPS_system_ila_0 || ORIG_REF_NAME==sync_counter_PPS_system_ila_0}]

# XDC: bd/sync_counter_PPS/sync_counter_PPS_ooc.xdc
