# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/sync_counter_PPS_system_ila_0.xci
# IP: The module: 'sync_counter_PPS_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/bd_6c1d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6c1d || ORIG_REF_NAME==bd_6c1d}]

# IP: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/ip/ip_0/bd_6c1d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6c1d_ila_lib_0 || ORIG_REF_NAME==bd_6c1d_ila_lib_0}]

# XDC: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6c1d_ila_lib_0 || ORIG_REF_NAME==bd_6c1d_ila_lib_0}] {/U0 }]/U0 ]]

# XDC: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/ip/ip_0/bd_6c1d_ila_lib_0_ooc.xdc

# XDC: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/bd_6c1d_ooc.xdc

# IP: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/sync_counter_PPS_system_ila_0.xci
# IP: The module: 'sync_counter_PPS_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/bd_6c1d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6c1d || ORIG_REF_NAME==bd_6c1d}]

# IP: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/ip/ip_0/bd_6c1d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6c1d_ila_lib_0 || ORIG_REF_NAME==bd_6c1d_ila_lib_0}]

# XDC: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6c1d_ila_lib_0 || ORIG_REF_NAME==bd_6c1d_ila_lib_0}] {/U0 }]/U0 ]]

# XDC: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/ip/ip_0/bd_6c1d_ila_lib_0_ooc.xdc

# XDC: /home/seba/documents/hepia/lora/lora_host_work/counter_PPS/counter_PPS.srcs/sources_1/bd/sync_counter_PPS/ip/sync_counter_PPS_system_ila_0/bd_0/bd_6c1d_ooc.xdc
