# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {BD 41-1348}  -string {{CRITICAL WARNING: [BD 41-1348] Reset pin /pps_counter_100mhz_0/rst (associated clock /pps_counter_100mhz_0/clk) is connected to asynchronous reset source /reset.
This may prevent design from meeting timing. Please add Processor System Reset module to create a reset that is synchronous to the associated clock source /clk_wiz_0/clk_out1.}}  -suppress 
set_msg_config  -ruleid {10}  -id {Vivado 12-1345}  -string {{ERROR: [Vivado 12-1345] Error(s) found during DRC. Bitgen not run.}}  -suppress 
set_msg_config  -ruleid {11}  -id {DRC 23-20}  -string {{ERROR: [DRC 23-20] Rule violation (UCIO-1) Unconstrained Logical Port - 5 out of 5 logical ports have no user assigned specific location constraint (LOC). This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all pin locations. This design will fail to generate a bitstream unless all logical ports have a user specified site LOC constraint defined.  To allow bitstream creation with unspecified pin locations (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks UCIO-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run.  Problem ports: clk, rst, jumper_i, led_o, pps_out.}}  -suppress 
set_msg_config  -ruleid {12}  -id {BD 41-758}  -string {{ERROR: [BD 41-758] The following clock pins are not connected to a valid clock source: 
/system_ila/clk}}  -suppress 
set_msg_config  -ruleid {13}  -id {BD 41-1031}  -string {{ERROR: [BD 41-1031] Hdl Generation failed for the IP Integrator design /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/pps_generator.bd}}  -suppress 
set_msg_config  -ruleid {14}  -id {Vivado 12-4756}  -string {{ERROR: [Vivado 12-4756] Launch of runs aborted due to earlier errors while preparing sub-designs for run execution.}}  -suppress 
set_msg_config  -ruleid {17}  -id {Labtools 27-2269}  -string {{ERROR: [Labtools 27-2269] No devices detected on target localhost:3121/xilinx_tcf/Digilent/210183741179A.
Check cable connectivity and that the target board is powered up then
use the disconnect_hw_server and connect_hw_server to re-register this hardware target.}}  -suppress 
set_msg_config  -ruleid {18}  -id {Labtoolstcl 44-513}  -string {{ERROR: [Labtoolstcl 44-513] HW Target shutdown. Closing target: localhost:3121/xilinx_tcf/Digilent/210183741179A}}  -suppress 
set_msg_config  -ruleid {19}  -id {Common 17-161}  -string {{CRITICAL WARNING: [Common 17-161] Invalid option value 'LVCMOS33' specified for 'objects'. [/home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/constrs_1/imports/new/basys3.xdc:155]}}  -suppress 
set_msg_config  -ruleid {20}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'U0/pps1_o_reg/Q' [/home/seba/documents/hepia/lora/pps_gen_fpga/pps_counter.vhd:64]}}  -suppress 
set_msg_config  -ruleid {21}  -id {Synth 8-5559}  -string {{CRITICAL WARNING: [Synth 8-5559] multi-driven net Q is connected to constant driver, other driver is ignored [/home/seba/documents/hepia/lora/pps_gen_fpga/pps_counter.vhd:64]}}  -suppress 
set_msg_config  -ruleid {22}  -id {Timing 38-282}  -string {{CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.}}  -suppress 
set_msg_config  -ruleid {3}  -id {BD 41-174}  -string {{ERROR: [BD 41-174] The name 'JB[0]' contains illegal characters.}}  -suppress 
set_msg_config  -ruleid {4}  -id {Coretcl 2-1280}  -string {{CRITICAL WARNING: [Coretcl 2-1280] The upgrade of 'module reference pps_generator_pps_counter_100mhz_0_0' has identified issues that may require user intervention. Please verify that the instance is correctly configured, and review any upgrade messages.}}  -suppress 
set_msg_config  -ruleid {7}  -id {Common 17-55}  -string {{CRITICAL WARNING: [Common 17-55] 'set_property' expects at least one object. [/home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/constrs_1/new/50ohm.xdc:7]
Resolution: If [get_<value>] was used to populate the object, check to make sure this command returns at least one valid object.}}  -suppress 
set_msg_config  -ruleid {8}  -id {Vivado 12-4739}  -string {{CRITICAL WARNING: [Vivado 12-4739] create_clock:No valid object(s) found for '-objects [get_ports CLK100MHZ]'. [/home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/constrs_1/new/50ohm.xdc:9]
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.}}  -suppress 
set_msg_config  -ruleid {9}  -id {DRC 23-20}  -string {{ERROR: [DRC 23-20] Rule violation (NSTD-1) Unspecified I/O Standard - 5 out of 5 logical ports use I/O standard (IOSTANDARD) value 'DEFAULT', instead of a user assigned specific value. This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all I/O standards. This design will fail to generate a bitstream unless all logical ports have a user specified I/O standard value defined. To allow bitstream creation with unspecified I/O standard values (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks NSTD-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run. Problem ports: clk, rst, jumper_i, led_o, pps_out.}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.cache/wt [current_project]
set_property parent.project_path /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/seba/documents/hepia/lora/pps_gen_fpga/gen_event_trigger.vhd
read_ip -quiet /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0.xci
set_property is_locked true [get_files /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.runs/pps_generator_gen_event_trigger_0_0_synth_1 -new_name pps_generator_gen_event_trigger_0_0 -ip [get_ips pps_generator_gen_event_trigger_0_0]]

if { $cached_ip eq {} } {

synth_design -top pps_generator_gen_event_trigger_0_0 -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix pps_generator_gen_event_trigger_0_0_ pps_generator_gen_event_trigger_0_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pps_generator_gen_event_trigger_0_0_stub.v
 lappend ipCachedFiles pps_generator_gen_event_trigger_0_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pps_generator_gen_event_trigger_0_0_stub.vhdl
 lappend ipCachedFiles pps_generator_gen_event_trigger_0_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pps_generator_gen_event_trigger_0_0_sim_netlist.v
 lappend ipCachedFiles pps_generator_gen_event_trigger_0_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ pps_generator_gen_event_trigger_0_0_sim_netlist.vhdl
 lappend ipCachedFiles pps_generator_gen_event_trigger_0_0_sim_netlist.vhdl

 config_ip_cache -add -dcp pps_generator_gen_event_trigger_0_0.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips pps_generator_gen_event_trigger_0_0]
}

rename_ref -prefix_all pps_generator_gen_event_trigger_0_0_

write_checkpoint -force -noxdef pps_generator_gen_event_trigger_0_0.dcp

catch { report_utilization -file pps_generator_gen_event_trigger_0_0_utilization_synth.rpt -pb pps_generator_gen_event_trigger_0_0_utilization_synth.pb }

if { [catch {
  file copy -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.runs/pps_generator_gen_event_trigger_0_0_synth_1/pps_generator_gen_event_trigger_0_0.dcp /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.runs/pps_generator_gen_event_trigger_0_0_synth_1/pps_generator_gen_event_trigger_0_0.dcp /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.runs/pps_generator_gen_event_trigger_0_0_synth_1/pps_generator_gen_event_trigger_0_0_stub.v /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.runs/pps_generator_gen_event_trigger_0_0_synth_1/pps_generator_gen_event_trigger_0_0_stub.vhdl /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.runs/pps_generator_gen_event_trigger_0_0_synth_1/pps_generator_gen_event_trigger_0_0_sim_netlist.v /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.runs/pps_generator_gen_event_trigger_0_0_synth_1/pps_generator_gen_event_trigger_0_0_sim_netlist.vhdl /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.ip_user_files/ip/pps_generator_gen_event_trigger_0_0]} {
  catch { 
    file copy -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_stub.v /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.ip_user_files/ip/pps_generator_gen_event_trigger_0_0
  }
}

if {[file isdir /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.ip_user_files/ip/pps_generator_gen_event_trigger_0_0]} {
  catch { 
    file copy -force /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.srcs/sources_1/bd/pps_generator/ip/pps_generator_gen_event_trigger_0_0/pps_generator_gen_event_trigger_0_0_stub.vhdl /home/seba/documents/hepia/lora/pps_gen_fpga/PPS_generator/PPS_generator.ip_user_files/ip/pps_generator_gen_event_trigger_0_0
  }
}
